<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <DefineConstants>TRIM_FEED</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ProgressTests.fs" />
    <Compile Include="StreamStateTests.fs" />
    <Compile Include="FsKafkaCodec.fs" />
    <Compile Include="SpanQueueTests.fs" />
    <Compile Include="ParallelThrottledValidation.fs" />
    <Compile Include="TestOutputLogger.fs" />
    <Compile Include="SourceTests.fs" />
    <Compile Include="SinkHealthTests.fs" />
    <Compile Include="AppendsIndexTests.fs" />
    <Compile Include="AppendsEpochTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Propulsion.DynamoStore\Propulsion.DynamoStore.fsproj" />
    <ProjectReference Include="..\..\src\Propulsion.MemoryStore\Propulsion.MemoryStore.fsproj" />
    <ProjectReference Include="..\..\src\Propulsion.Kafka\Propulsion.Kafka.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit.v3" Version="3.3.3" />
    <PackageReference Include="unquote" Version="6.1.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

</Project>
