// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Confluent.Kafka.FSharp")>]
[<assembly: AssemblyProductAttribute("confluent-kafka-fsharp")>]
[<assembly: AssemblyDescriptionAttribute("Lightweight F# wrapper for Confluent.Kafka")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Confluent.Kafka.FSharp"
    let [<Literal>] AssemblyProduct = "confluent-kafka-fsharp"
    let [<Literal>] AssemblyDescription = "Lightweight F# wrapper for Confluent.Kafka"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
