<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <DisableImplicitFSharpCoreReference>false</DisableImplicitFSharpCoreReference>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Propulsion.Tests\TestOutputLogger.fs">
      <Link>TestOutputLogger.fs</Link>
    </Compile>
    <Compile Include="ConsumersIntegration.fs" />
    <Compile Include="MonitorIntegration.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Propulsion.Kafka\Propulsion.Kafka.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="unquote" Version="6.1.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="7.0.0" />
  </ItemGroup>

</Project>
